version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka_exporter:
    image: danielqsj/kafka-exporter
    ports:
      - '9308:9308'
    depends_on:
      - kafka
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/Utils/scripts/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka_exporter
      - alertmanager
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    depends_on:
      - kafka_exporter

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - $PWD/plugin:/var/lib/grafana/plugins
    depends_on:
      - prometheus

  kafka-testbed:
    image: svansig/kafka-testbed
    ports:
      - '2022:2022'
